version: '3'
services:
  tiktok-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiktok-sync
    restart: always
    environment:
      - PORT=5000
      - DB_TYPE=mysql
      - DB_HOST=103.67.196.23
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=Thanhtho96@1111
      - DB_DATABASE=homstay
      - NODE_OPTIONS=--max-old-space-size=4096
      - ENV=production
      - REDIS_HOST=103.67.196.23
      - REDIS_PORT=6379
      - REDIS_TYPE=single
      - IP_SOCKET=localhost
      - PORT_SOCKET=2000
    ports:
      - '5000:5000'
