export type Person = {
    firstName: string;
    lastName: string;
    age: number;
    gender: string;
    state: string;
    salary: number;
  };
  
  export const data: Person[] = [
    {
      firstName: 'Danika',
      lastName: 'Rodriguez',
      age: 57,
      gender: 'Male',
      state: 'Utah',
      salary: 31404,
    },
    {
      firstName: 'Eloisa',
      lastName: 'Kohler',
      age: 31,
      gender: 'Male',
      state: 'Alaska',
      salary: 45801,
    },
    {
      firstName: 'Gunner',
      lastName: 'Rolfson',
      age: 22,
      gender: 'Male',
      state: 'Arizona',
      salary: 54027,
    },
    {
      firstName: 'Andreanne',
      lastName: 'Hamill',
      age: 65,
      gender: 'Female',
      state: 'Hawaii',
      salary: 60975,
    },
    {
      firstName: 'Kali',
      lastName: 'Jones',
      age: 56,
      gender: 'Female',
      state: 'Kentucky',
      salary: 27067,
    },
    {
      firstName: 'Felicia',
      lastName: 'Mitchell',
      age: 34,
      gender: 'Male',
      state: 'South Carolina',
      salary: 48423,
    },
    {
      firstName: 'Philip',
      lastName: 'Koepp',
      age: 32,
      gender: 'Male',
      state: 'Louisiana',
      salary: 36713,
    },
    {
      firstName: 'Aniya',
      lastName: 'Mante',
      age: 41,
      gender: 'Female',
      state: 'Minnesota',
      salary: 77658,
    },
    {
      firstName: 'Nelda',
      lastName: 'Gottlieb',
      age: 41,
      gender: 'Female',
      state: 'Delaware',
      salary: 57634,
    },
    {
      firstName: 'Marty',
      lastName: 'Kihn',
      age: 19,
      gender: 'Male',
      state: 'Delaware',
      salary: 95427,
    },
    {
      firstName: 'Alvis',
      lastName: 'Turcotte',
      age: 53,
      gender: 'Female',
      state: 'Wyoming',
      salary: 14272,
    },
    {
      firstName: 'Kavon',
      lastName: 'Spencer',
      age: 37,
      gender: 'Female',
      state: 'Missouri',
      salary: 79499,
    },
    {
      firstName: 'Winifred',
      lastName: 'Wilderman',
      age: 56,
      gender: 'Female',
      state: 'Iowa',
      salary: 96293,
    },
    {
      firstName: 'Brooklyn',
      lastName: 'Monahan',
      age: 35,
      gender: 'Female',
      state: 'Nevada',
      salary: 13219,
    },
    {
      firstName: 'Santino',
      lastName: 'Brown',
      age: 33,
      gender: 'Male',
      state: 'Mississippi',
      salary: 36361,
    },
    {
      firstName: 'Bianka',
      lastName: 'Yost',
      age: 28,
      gender: 'Female',
      state: 'Wisconsin',
      salary: 89057,
    },
    {
      firstName: 'Herman',
      lastName: 'Herzog',
      age: 63,
      gender: 'Female',
      state: 'South Carolina',
      salary: 28110,
    },
    {
      firstName: 'Earl',
      lastName: 'Gottlieb',
      age: 65,
      gender: 'Female',
      state: 'Florida',
      salary: 31400,
    },
    {
      firstName: 'Valentine',
      lastName: 'Bauch',
      age: 61,
      gender: 'Female',
      state: 'North Carolina',
      salary: 35130,
    },
    {
      firstName: 'Joanny',
      lastName: 'Koss',
      age: 23,
      gender: 'Male',
      state: 'Colorado',
      salary: 90422,
    },
    {
      firstName: 'Aliza',
      lastName: 'Wilkinson',
      age: 25,
      gender: 'Female',
      state: 'Virginia',
      salary: 98417,
    },
    {
      firstName: 'Eldred',
      lastName: 'Collier',
      age: 37,
      gender: 'Male',
      state: 'Mississippi',
      salary: 43741,
    },
    {
      firstName: 'Dorris',
      lastName: 'Koch',
      age: 37,
      gender: 'Male',
      state: 'Delaware',
      salary: 40979,
    },
    {
      firstName: 'Felix',
      lastName: 'Zieme',
      age: 51,
      gender: 'Male',
      state: 'Ohio',
      salary: 55319,
    },
    {
      firstName: 'Salma',
      lastName: 'Treutel',
      age: 32,
      gender: 'Female',
      state: 'Pennsylvania',
      salary: 31722,
    },
    {
      firstName: 'Durward',
      lastName: 'Kris',
      age: 36,
      gender: 'Male',
      state: 'Iowa',
      salary: 28486,
    },
    {
      firstName: 'Osborne',
      lastName: 'Barrows',
      age: 28,
      gender: 'Male',
      state: 'West Virginia',
      salary: 43996,
    },
    {
      firstName: 'Adelia',
      lastName: 'Abbott',
      age: 38,
      gender: 'Male',
      state: 'Oregon',
      salary: 34720,
    },
    {
      firstName: 'Thad',
      lastName: 'Wiegand',
      age: 64,
      gender: 'Female',
      state: 'Alabama',
      salary: 56146,
    },
    {
      firstName: 'Tiana',
      lastName: 'Tromp',
      age: 51,
      gender: 'Male',
      state: 'Arkansas',
      salary: 45636,
    },
    {
      firstName: 'Gwen',
      lastName: 'Bergstrom',
      age: 36,
      gender: 'Female',
      state: 'Wyoming',
      salary: 95145,
    },
    {
      firstName: 'Evalyn',
      lastName: 'Mitchell',
      age: 53,
      gender: 'Female',
      state: 'Illinois',
      salary: 86990,
    },
    {
      firstName: 'Edyth',
      lastName: 'Macejkovic',
      age: 55,
      gender: 'Female',
      state: 'Kentucky',
      salary: 65344,
    },
    {
      firstName: 'Lamar',
      lastName: 'Bechtelar',
      age: 58,
      gender: 'Female',
      state: 'Rhode Island',
      salary: 93753,
    },
    {
      firstName: 'Tillman',
      lastName: 'Jacobs',
      age: 36,
      gender: 'Female',
      state: 'New Mexico',
      salary: 13393,
    },
    {
      firstName: 'Turner',
      lastName: 'Haley',
      age: 56,
      gender: 'Female',
      state: 'Nebraska',
      salary: 93733,
    },
    {
      firstName: 'Omer',
      lastName: 'Funk',
      age: 28,
      gender: 'Female',
      state: 'Iowa',
      salary: 77913,
    },
    {
      firstName: 'Alivia',
      lastName: 'Ledner',
      age: 56,
      gender: 'Male',
      state: 'Alabama',
      salary: 12591,
    },
    {
      firstName: 'Dortha',
      lastName: 'Schmitt',
      age: 43,
      gender: 'Male',
      state: 'Mississippi',
      salary: 80347,
    },
    {
      firstName: 'Ellie',
      lastName: 'Schinner',
      age: 41,
      gender: 'Female',
      state: 'Rhode Island',
      salary: 42232,
    },
    {
      firstName: 'Pansy',
      lastName: 'Reilly',
      age: 55,
      gender: 'Male',
      state: 'Louisiana',
      salary: 87255,
    },
    {
      firstName: 'Alfonzo',
      lastName: 'Abernathy',
      age: 40,
      gender: 'Male',
      state: 'Utah',
      salary: 53374,
    },
    {
      firstName: 'Carmine',
      lastName: 'Orn',
      age: 24,
      gender: 'Female',
      state: 'Georgia',
      salary: 89363,
    },
    {
      firstName: 'Taylor',
      lastName: 'Herzog',
      age: 63,
      gender: 'Male',
      state: 'Florida',
      salary: 81429,
    },
    {
      firstName: 'Ray',
      lastName: 'Little',
      age: 27,
      gender: 'Female',
      state: 'Maine',
      salary: 53736,
    },
    {
      firstName: 'Melyssa',
      lastName: 'Bechtelar',
      age: 56,
      gender: 'Male',
      state: 'New Mexico',
      salary: 85152,
    },
    {
      firstName: 'Coy',
      lastName: 'Schoen',
      age: 32,
      gender: 'Male',
      state: 'Florida',
      salary: 83999,
    },
    {
      firstName: 'Lexi',
      lastName: 'Reinger',
      age: 39,
      gender: 'Female',
      state: 'Virginia',
      salary: 17585,
    },
    {
      firstName: 'Carlee',
      lastName: 'Turcotte',
      age: 25,
      gender: 'Male',
      state: 'Missouri',
      salary: 85236,
    },
    {
      firstName: 'Tamia',
      lastName: 'Stamm',
      age: 47,
      gender: 'Female',
      state: 'Nevada',
      salary: 65037,
    },
    {
      firstName: 'Leola',
      lastName: 'Donnelly',
      age: 30,
      gender: 'Female',
      state: 'Missouri',
      salary: 23897,
    },
    {
      firstName: 'Allison',
      lastName: 'Stanton',
      age: 34,
      gender: 'Male',
      state: 'New Hampshire',
      salary: 34389,
    },
    {
      firstName: 'Neoma',
      lastName: 'Flatley',
      age: 65,
      gender: 'Female',
      state: 'Connecticut',
      salary: 43669,
    },
    {
      firstName: 'Brad',
      lastName: 'Altenwerth',
      age: 18,
      gender: 'Male',
      state: 'Virginia',
      salary: 85599,
    },
    {
      firstName: 'Magdalen',
      lastName: 'Berge',
      age: 58,
      gender: 'Female',
      state: 'Louisiana',
      salary: 65571,
    },
    {
      firstName: 'Kathryn',
      lastName: 'Kirlin',
      age: 48,
      gender: 'Female',
      state: 'New Hampshire',
      salary: 97434,
    },
    {
      firstName: 'Rod',
      lastName: 'Sawayn',
      age: 19,
      gender: 'Female',
      state: 'Nevada',
      salary: 58951,
    },
    {
      firstName: 'Georgette',
      lastName: 'Beatty',
      age: 53,
      gender: 'Male',
      state: 'Kentucky',
      salary: 12203,
    },
    {
      firstName: 'Dianna',
      lastName: 'King',
      age: 23,
      gender: 'Female',
      state: 'Vermont',
      salary: 13515,
    },
    {
      firstName: 'Kellie',
      lastName: 'Parker',
      age: 43,
      gender: 'Trans Male',
      state: 'Louisiana',
      salary: 49457,
    },
    {
      firstName: 'Faustino',
      lastName: 'Ankunding',
      age: 43,
      gender: 'Male',
      state: 'Indiana',
      salary: 49943,
    },
    {
      firstName: 'Hilton',
      lastName: 'Pacocha',
      age: 58,
      gender: 'Male',
      state: 'South Dakota',
      salary: 34874,
    },
    {
      firstName: 'Shanel',
      lastName: 'Schneider',
      age: 33,
      gender: 'Female',
      state: 'Nebraska',
      salary: 50446,
    },
    {
      firstName: 'Wade',
      lastName: 'Kiehn',
      age: 23,
      gender: 'Male',
      state: 'Delaware',
      salary: 29522,
    },
    {
      firstName: 'Austyn',
      lastName: 'Rempel',
      age: 35,
      gender: 'Female',
      state: 'Arkansas',
      salary: 42997,
    }
  ];
  